import React from 'react';
import { FileText } from 'lucide-react';

export function ReportsPage({
  incidents,
  selectedIncident,
  setSelectedIncident
}) {
  return (
    <div className="space-y-6">
      <div className="border-b border-stone-200 pb-4">
        <h2 className="text-2xl font-bold text-abstra-dark font-display">Incident Reports</h2>
        <p className="text-abstra-muted text-xs mt-1">Review post-mortem documents, root causes, and remediation actions generated by Ollama LLM.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left: List */}
        <div className="bg-white border border-stone-200 rounded-2xl p-4 h-[500px] overflow-y-auto space-y-2">
          <span className="text-xs font-bold text-abstra-dark px-2 block mb-3 uppercase tracking-wider font-display">Analyzed Incidents</span>
          {incidents.filter(i => i.ai_analysis).length === 0 ? (
            <div className="text-center py-12 text-xs text-abstra-muted font-mono">
              No post-mortems generated yet. Trigger AI analysis on active incidents.
            </div>
          ) : (
            incidents.filter(i => i.ai_analysis).map((incident) => (
              <button
                key={incident.id}
                onClick={() => setSelectedIncident(incident)}
                className={`w-full text-left p-3.5 rounded-xl border transition flex flex-col space-y-1 ${
                  selectedIncident?.id === incident.id 
                    ? 'bg-abstra-sand/40 border-abstra-terracotta/50 font-bold' 
                    : 'bg-stone-50 border-stone-200/60 hover:bg-stone-100 text-abstra-dark'
                }`}
              >
                <div className="flex justify-between items-center">
                  <span className="font-mono text-xs font-bold">{incident.id}</span>
                  <span className="text-[10px] text-abstra-muted font-mono">{incident.timestamp.split('T')[0]}</span>
                </div>
                <span className="text-xs font-medium text-abstra-dark truncate">{incident.service}</span>
              </button>
            ))
          )}
        </div>

        {/* Right: Selected details */}
        <div className="lg:col-span-2 bg-white border border-stone-200 rounded-2xl p-6 h-[500px] overflow-y-auto flex flex-col">
          {selectedIncident && selectedIncident.ai_analysis ? (
            <div className="space-y-6">
              <div className="border-b border-stone-200 pb-4 flex justify-between items-start">
                <div>
                  <h3 className="text-lg font-bold text-abstra-dark font-display">{selectedIncident.service} Post-Mortem</h3>
                  <span className="text-xs text-abstra-muted font-mono">ID: {selectedIncident.id} | Timestamp: {selectedIncident.timestamp}</span>
                </div>
                <span className="text-xs font-semibold px-3 py-1 bg-signal-teal/15 text-signal-teal rounded-full font-mono">
                  Confidence: {Math.round(selectedIncident.ai_analysis.confidence_score * 100)}%
                </span>
              </div>

              <div className="space-y-2">
                <span className="text-xs font-bold text-abstra-dark uppercase tracking-wider font-display">Probable Root Cause</span>
                <div className="bg-canvas-card border border-stone-200 rounded-xl p-4 text-xs font-mono text-abstra-dark">
                  {selectedIncident.ai_analysis.root_cause}
                </div>
              </div>

              <div className="space-y-3">
                <span className="text-xs font-bold text-abstra-dark uppercase tracking-wider font-display font-semibold">Full Incident Report</span>
                <div className="bg-stone-50 p-5 rounded-2xl border border-stone-200 text-abstra-dark text-xs font-mono whitespace-pre-wrap leading-relaxed">
                  {selectedIncident.ai_analysis.incident_report}
                </div>
              </div>
            </div>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-center text-abstra-muted font-mono">
              <FileText className="h-8 w-8 text-abstra-mauve mb-3" />
              <span className="text-xs">Select an incident report from the list to view post-mortem details.</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
